## 3.1

- We are in function call `greet2` and there is variable `name: Maggie` stored
- It was called in a `greet` function where there is variable `name: Maggie` as well
- Both function were not completed yet

## 3.2

After certain number of calls is exceeded, you will get a famous stack overflow error and program will exit.
